/* Create table which will contain info about total quantity ordered for each day/date, 
avg quantity ordered for each day/date,
total revenue for each day/date,
avg_revenue for each day/daten
*/
CREATE TABLE orders_review 
	SELECT date, SUM(quantity) AS 'total_quantity_sold',
	ROUND(AVG(quantity),2) AS 'avg_quantity_per_order',
	ROUND(AVG(order_version_id),2) AS 'avg_number_of_versions_per_order',
	SUM(total) AS 'total_revenue',
	ROUND(AVG(total),2) AS 'avg_revenue_per_order',
	FROM product_orders
	WHERE valid_to = '9999-01-01'
	GROUP BY date
	ORDER BY AVG(total)
	
/* quantity of each product sold in specific time period, total revenue generated by the product and margin */
SELECT p.product_name,
SUM(p.quantity) AS 'quantity_of_product_sold',
SUM(p.quantity * p.price) AS 'revenue',
ROUND((1-(p.netto_netto_price / p.price))*100,2) AS 'margin_%'
FROM positions as p
JOIN product_orders AS po
ON p.position_id = po.id
WHERE po.date BETWEEN '2021-01-01' AND '2021-12-01'
GROUP BY p.product_name
ORDER BY SUM(p.quantity) DESC